#!/usr/bin/env python

'''Lesson management script.'''


import sys
import os

LESSON_DIR = 'lessons' # lesson directory within installation directory


def main(argv):
    '''Main command driver.'''
    try:
        assert len(argv) > 1, \
            'Must have command name.'
        cmd, args = argv[1], argv[2:]
        assert cmd in COMMANDS, \
            'Unknown command: "{0}"'.format(cmd)
        COMMANDS[cmd](*args)
    except Exception, e:
        fail(str(e))

def _help():
    '''help: display help.'''
    print USAGE


def files(lesson, root_dir=None):
    '''files <lesson_name> [<install_directory>]: make local copy of files for lesson.'''
    if root_dir is None:
        root_dir = os.curdir
    print 'Copying files for "{0}" to "{1}".'.format(lesson, root_dir)


def view(*args):
    '''view <lesson>: open lesson in browser.'''
    assert len(args) == 1, \
        'Command "view" requires exactly one lesson name'
    lesson_name = args[0]
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
    lesson_dir = os.path.join(root, LESSON_DIR, lesson_name)
    assert os.path.isdir(lesson_dir), \
        'No such lesson "{0}" at "{1}"'.format(lesson_name, lesson_dir)
    index_page = os.path.join(lesson_dir, 'index.html')
    assert os.path.isfile(index_page), \
        'No index.html page for lesson "{0}" at "{1}"'.format(lesson_name, index_page)
    import webbrowser
    webbrowser.open('file://' + index_page)


def fail(message):
    '''Check and fail.'''
    print >> sys.stderr, message
    print >> sys.stderr, USAGE
    sys.exit(1)


COMMANDS = {
    'help'  : _help,
    'view'  : view,
    'files' : files
}


USAGE = '''Usage: lesson command [args]
{0}
See https://github.com/gvwilson/lesson-installer-demo for more documentation.'''\
.format('\n'.join('  {:8}: {}'.format(c, COMMANDS[c].__doc__) for c in COMMANDS))


if __name__ == '__main__':
    main(sys.argv)
