#!/usr/bin/env python

'''Lesson management script.'''

import sys

USAGE = '''Usage: lesson command [args]
{0}
See <FIXME> for more documentation.'''


def main(argv):
    '''Main command driver.'''
    require(len(argv) > 1)
    cmd, args = argv[1], argv[2:]
    require(cmd in COMMANDS, 'Unknown command: "{0}"'.format(cmd))
    COMMANDS[cmd](*args)


def usage():
    '''Display usage and exit.'''
    print USAGE


def files(lesson_name, root_dir=None):
    '''Get local copy of files for lesson.'''
    if root_dir is None:
        root_dir = os.curdir
    print 'Copying files for "{0}" to "{1}".'.format(lesson_name, root_dir)


def view(lesson_name):
    '''Open lesson in browser.'''
    print 'Displaying "{0}" in browser.'.format(lesson_name)


def require(condition, *messages):
    '''Check and fail.'''
    if not condition:
        for m in messages:
            print m
        usage = USAGE.format('\n'.join('  {:8}: {}'.format(c, COMMANDS[c].__doc__) for c in COMMANDS))
        print usage
        sys.exit(1)


COMMANDS = {
    'help'  : usage,
    'view'  : view,
    'files' : files
}


if __name__ == '__main__':
    main(sys.argv)
